# Generated by Django 3.0.5 on 2020-05-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelinfo',
            fields=[
                ('hotelid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hotelname', models.CharField(default=None, max_length=40)),
                ('loc', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
