# Generated by Django 3.0.5 on 2020-05-18 05:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roominformation',
            fields=[
                ('roomid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('roomtype', models.CharField(db_column='RoomType', max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='pics')),
                ('sdate', models.DateField(default=datetime.date.today)),
                ('edate', models.DateField(default=datetime.date.today)),
                ('is_reserved', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='userform.Hotelinfo')),
            ],
        ),
    ]
