# Generated by Django 3.0.5 on 2020-05-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_roominformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominformation',
            name='is_reserved',
        ),
    ]
