# Generated by Django 3.0.5 on 2020-05-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0003_remove_roominformation_is_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdetails1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('address1', models.CharField(max_length=100)),
                ('hotel1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userform.Hotelinfo')),
                ('room1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userform.Roominformation')),
            ],
        ),
    ]
