# Generated by Django 3.0.5 on 2020-05-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0004_bookingdetails1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails1',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingdetails1',
            name='hotel1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel1', to='userform.Hotelinfo'),
        ),
        migrations.AlterField(
            model_name='bookingdetails1',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingdetails1',
            name='room1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room1', to='userform.Roominformation'),
        ),
        migrations.AlterField(
            model_name='bookingdetails1',
            name='user_name',
            field=models.CharField(max_length=1000),
        ),
    ]
